env_str: room_env:RoomEnv-v1
num_iterations: 2048
replay_buffer_size: 1024
warm_start: 1024
batch_size: 1024
target_update_interval: 10
epsilon_decay_until: 1024
max_epsilon: 1.0
min_epsilon: 0.1
gamma: 0.65
capacity:
  episodic: 16
  semantic: 16
  short: 1
pretrain_semantic: false
nn_params:
  hidden_size: 64
  num_layers: 2
  embedding_dim: 32
  include_human: sum
  human_embedding_on_object_location: false
  include_positional_encoding: false
  max_timesteps: null
  max_strength: null
run_test: true
num_samples_for_results: 10
plotting_interval: 10
train_seed: 5
test_seed: 0
device: cpu
ddqn: true
dueling_dqn: true
